name: declenchementManuelSite

on:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Aller au site internet
        run: curl wttr.in/Moon


