name: builder application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installer python 
        uses: actions/setup-python@4
        
      - name: Installer Flask 
        run: pip install flask

      - name: Check syntax 
        run: python projet.py check_syntax 
