name: builder application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
      
      - name: Install Flask 
        run: python -m pip install -r requirements.txt

      - name: Check syntax 
        run: python projet.py check_syntax 
